version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 14330:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    volumes:
      - db-data:/var/opt/mssql
volumes:
  db-data:
    external: true