version: '3'
services:
  mydb:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
volumes:
  db-data:
    external: true